name: SpotDL Music Downloader

on:
  workflow_dispatch:
    inputs:
      spotify_url:
        description: 'Spotify Song/Playlist/Album URL'
        required: true
        type: string

jobs:
  download_music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install spotdl
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade spotdl

      - name: Install yt-dlp nightly
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Check versions
        run: |
          python --version
          spotdl --version
          yt-dlp --version
          ffmpeg -version

      - name: Create download directory
        run: mkdir -p music-downloads

      - name: Download music using spotdl
        run: |
          echo "Attempting to download from: ${{ github.event.inputs.spotify_url }}"
          spotdl download "${{ github.event.inputs.spotify_url }}" --output ./music-downloads --log-level INFO

      - name: List files in download directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents of ./music-downloads/:"
          ls -la ./music-downloads/
          echo "Listing contents of current directory:"
          ls -la .

      - name: Upload Music Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-music
          path: ./music-downloads/
          retention-days: 7
          if-no-files-found: error
