name: SpotDL Music Downloader

on:
  workflow_dispatch:
    inputs:
      spotify_url:
        description: 'Spotify Song/Playlist/Album URL'
        required: true
        type: string

jobs:
  download_music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Step 4: Install/Upgrade spotdl AND yt-dlp
      - name: Install/Upgrade spotdl and yt-dlp
        run: |
          pip install --upgrade pip # Ensure pip is up to date
          pip install --upgrade spotdl yt-dlp # Install or upgrade both packages

      # Optional: Check versions after upgrade
      - name: Check versions
        run: |
          spotdl --version
          yt-dlp --version

      - name: Create download directory
        run: mkdir music-downloads

      - name: Download music using spotdl
        run: |
          echo "Attempting to download from: ${{ github.event.inputs.spotify_url }}"
          # Using INFO level logging is usually sufficient
          spotdl download "${{ github.event.inputs.spotify_url }}" --output ./music-downloads --log-level INFO

      # Debugging Step (Keep it for now)
      - name: List files in download directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents of ./music-downloads/:"
          ls -la ./music-downloads/
          echo "Listing contents of current directory:"
          ls -la .

      - name: Upload Music Artifact
        # Only run upload if the download step was successful (default behavior)
        # or if the download directory actually contains files (more robust check)
        # Using default behavior is usually fine if download step fails on error.
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-music
          path: ./music-downloads/
          retention-days: 7
          if-no-files-found: error # Fail the workflow if the directory is empty
